"""
Cohort-level HTML QC report.

Generates a publication-quality group summary suitable as a data-quality
appendix in multicenter studies.  All plots are embedded as base64 PNGs
and the HTML is fully self-contained (no CDN links).
"""
import base64
import datetime
import io
import logging
import math
from pathlib import Path

import numpy as np

log = logging.getLogger(__name__)

__version__ = "0.3.0"


def write_cohort_html(cohort_results, path):
    """Write a self-contained cohort QC HTML report."""
    ts = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
    n = cohort_results.get("n_subjects", 0)
    summary = cohort_results.get("summary", {})
    subjects = cohort_results.get("subjects", [])
    metric_summary = cohort_results.get("metric_summary", {})
    if_results = cohort_results.get("isolation_forest")

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>ASL QC — Cohort Report ({n} subjects)</title>
{_css()}
</head>
<body>
<div class="container">

<h1>ASL Quality Control — Cohort Report</h1>
<p class="meta">
    ASL QC Toolbox v{__version__} &middot; {n} subjects &middot; {ts}
</p>

{_dataset_summary(summary, n)}
{_metric_summary_table(metric_summary)}
{_distribution_plots(subjects, metric_summary)}
{_correlation_matrix(subjects)}
{_anomaly_section(subjects, if_results)}
{_subject_table(subjects)}
{_methods_footnote()}

<div class="footer">
Generated by ASL QC Toolbox v{__version__} &middot; {ts}
</div>
</div>
{_sort_js()}
</body>
</html>"""

    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    with open(p, "w") as f:
        f.write(html)
    log.info("cohort html -> %s", p)
    return str(p)


# ──────────────────────────────────────────────
# CSS
# ──────────────────────────────────────────────

def _css():
    return """<style>
* { box-sizing: border-box; margin: 0; padding: 0; }
body {
    font-family: 'Inter', system-ui, -apple-system, sans-serif;
    background: #fff; color: #1a1a1a;
    max-width: 1100px; margin: 0 auto; padding: 32px 24px;
    font-size: 13px; line-height: 1.6;
}
.container { max-width: 1100px; }
h1 { font-size: 24px; font-weight: 600; margin-bottom: 4px; }
h2 {
    font-size: 14px; font-weight: 600; text-transform: uppercase;
    letter-spacing: 0.08em; color: #555;
    margin: 28px 0 10px; padding-bottom: 6px;
    border-bottom: 1px solid #ddd;
}
.meta { color: #888; font-size: 12px; margin-bottom: 12px; }
.summary-grid {
    display: grid; grid-template-columns: repeat(5, 1fr);
    gap: 8px; margin: 12px 0;
}
.summary-item { text-align: center; padding: 8px; }
.summary-value { font-size: 22px; font-weight: 600; font-family: 'SF Mono', monospace; }
.summary-label { font-size: 11px; color: #888; text-transform: uppercase; letter-spacing: 0.05em; }
table { width: 100%; border-collapse: collapse; margin: 8px 0; }
th {
    font-size: 11px; font-weight: 600; text-transform: uppercase;
    letter-spacing: 0.05em; color: #666;
    text-align: left; padding: 6px 8px;
    border-bottom: 2px solid #333;
    cursor: pointer; user-select: none;
}
th:hover { color: #000; }
th .sort-arrow { font-size: 10px; margin-left: 2px; }
td {
    padding: 4px 8px; font-size: 12px;
    border-bottom: 1px solid #eee;
}
td.val { font-family: 'SF Mono', 'Consolas', monospace; font-size: 11px; }
.status-pass { color: #2e7d32; }
.status-warning { color: #e65100; }
.status-fail { color: #b71c1c; }
tr.flagged { border-left: 3px solid #b71c1c; }
.plot-grid {
    display: grid; grid-template-columns: 1fr 1fr;
    gap: 16px; margin: 12px 0;
}
.plot-cell img { max-width: 100%; border: 1px solid #eee; border-radius: 2px; }
.methods {
    font-size: 11px; color: #999; line-height: 1.5;
    margin-top: 24px; padding-top: 12px;
    border-top: 1px solid #eee;
}
.footer {
    font-size: 10px; color: #bbb; text-align: center;
    margin-top: 20px; padding-top: 8px;
    border-top: 1px solid #f0f0f0;
}
.anomaly-container { position: relative; }
.anomaly-container svg { max-width: 100%; }
.tooltip {
    position: absolute; display: none;
    background: rgba(0,0,0,0.85); color: #fff;
    padding: 4px 8px; border-radius: 3px;
    font-size: 11px; font-family: 'SF Mono', monospace;
    pointer-events: none; white-space: nowrap; z-index: 10;
}
</style>"""


# ──────────────────────────────────────────────
# Dataset summary
# ──────────────────────────────────────────────

def _dataset_summary(summary, n):
    n_pass = summary.get("n_pass", 0)
    n_warn = summary.get("n_warning", 0)
    n_fail = summary.get("n_fail", 0)
    pct = summary.get("pct_flagged", 0)

    return f"""
<h2>Dataset Summary</h2>
<div class="summary-grid">
    <div class="summary-item">
        <div class="summary-value">{n}</div>
        <div class="summary-label">Total</div>
    </div>
    <div class="summary-item">
        <div class="summary-value status-pass">{n_pass}</div>
        <div class="summary-label">Pass</div>
    </div>
    <div class="summary-item">
        <div class="summary-value status-warning">{n_warn}</div>
        <div class="summary-label">Warning</div>
    </div>
    <div class="summary-item">
        <div class="summary-value status-fail">{n_fail}</div>
        <div class="summary-label">Fail</div>
    </div>
    <div class="summary-item">
        <div class="summary-value" style="color:#888">{pct:.1f}%</div>
        <div class="summary-label">Flagged</div>
    </div>
</div>
"""


# ──────────────────────────────────────────────
# Metric summary table
# ──────────────────────────────────────────────

_METRIC_LABELS = {
    "snr": "SNR (raw EPI)",
    "spatial_cov": "Spatial CoV",
    "negative_fraction": "Negative fraction",
    "dvars_spike_fraction": "DVARS spike frac.",
    "skewness": "Skewness",
    "qei": "QEI",
    "tsnr": "tSNR",
    "mean_fd": "Mean FD (mm)",
}

def _metric_summary_table(metric_summary):
    if not metric_summary:
        return ""

    rows = []
    for key, label in _METRIC_LABELS.items():
        ms = metric_summary.get(key)
        if ms is None:
            continue
        rows.append(
            f'<tr>'
            f'<td>{label}</td>'
            f'<td class="val">{ms["median"]:.3f}</td>'
            f'<td class="val">{ms["iqr"]:.3f}</td>'
            f'<td class="val">{ms["mean"]:.3f} ± {ms["std"]:.3f}</td>'
            f'<td class="val">{ms["n_available"]}</td>'
            f'</tr>'
        )

    return f"""
<h2>Per-Metric Summary</h2>
<table>
<tr><th>Metric</th><th>Median</th><th>IQR</th><th>Mean ± SD</th><th>N available</th></tr>
{"".join(rows)}
</table>
"""


def _distribution_plots(subjects, metric_summary):
    """One unified MRIQC-style panel with all key ASL metrics side-by-side."""
    if not subjects or len(subjects) < 2:
        return ""

    try:
        plt = _setup_mpl()
    except Exception:
        return ""

    # only the metrics that matter for ASL QC
    # (skewness, kurtosis, QEI are derivative/composite — not needed here)
    panels = [
        ("snr",                  "SNR",       "#5b9bd5"),
        ("spatial_cov",          "CoV",       "#5b9bd5"),
        ("tsnr",                 "tSNR",      "#5b9bd5"),
        ("negative_fraction",    "Neg frac",  "#ed7d31"),
        ("dvars_spike_fraction", "DVARS spk", "#ed7d31"),
        ("mean_fd",              "FD (mm)",   "#70ad47"),
    ]

    # collect data and filter to panels that have values
    panel_data = []
    for key, label, color in panels:
        vals = []
        statuses = []
        for s in subjects:
            v = s.get(key)
            if v is not None and _is_finite(v):
                vals.append(v)
                statuses.append(s.get("status", "PASS"))
        if len(vals) >= 2:
            panel_data.append((key, label, color, vals, statuses))

    if not panel_data:
        return ""

    n = len(panel_data)
    fig, axes = plt.subplots(1, n, figsize=(2.2 * n, 4.5))
    if n == 1:
        axes = [axes]

    status_colors = {"PASS": "#4caf50", "WARNING": "#ff9800", "FAIL": "#e53935"}
    rng = np.random.RandomState(42)

    for ax, (key, label, base_color, vals, statuses) in zip(axes, panel_data):
        arr = np.array(vals)
        colors = [status_colors.get(st, "#999") for st in statuses]

        # box plot: clean, light fill, no outlier markers
        bp = ax.boxplot(arr, positions=[0], widths=[0.35], vert=True,
                        patch_artist=True, showfliers=False,
                        showmeans=True,
                        meanprops=dict(marker="o", markerfacecolor="white",
                                       markeredgecolor="#333", markersize=5),
                        medianprops=dict(color="#333", linewidth=1.5),
                        whiskerprops=dict(color="#aaa", linewidth=0.8),
                        capprops=dict(color="#aaa", linewidth=0.8))
        bp["boxes"][0].set(facecolor="#f0f0f0", edgecolor="#bbb",
                           linewidth=0.7, alpha=0.7)

        # jittered dots
        jitter = rng.uniform(-0.14, 0.14, size=len(vals))
        ax.scatter(jitter, vals, c=colors, s=10, alpha=0.7,
                   edgecolors="none", zorder=3)

        ax.set_xticks([0])
        ax.set_xticklabels([label], fontsize=9, fontweight="600")
        ax.set_xlim(-0.5, 0.5)
        ax.tick_params(axis="y", labelsize=8)
        ax.spines["top"].set_visible(False)
        ax.spines["right"].set_visible(False)
        ax.spines["bottom"].set_visible(False)
        ax.yaxis.grid(True, alpha=0.15, linewidth=0.5)

    fig.tight_layout(w_pad=1.0)

    b64 = _fig_to_b64(fig)
    return f"""
<h2>Metric Distributions</h2>
<img src="data:image/png;base64,{b64}" alt="Metric distributions"
     style="max-width:100%; border:1px solid #eee; border-radius:2px">
"""


# ──────────────────────────────────────────────
# Correlation matrix
# ──────────────────────────────────────────────

def _correlation_matrix(subjects):
    if not subjects or len(subjects) < 5:
        return ""

    try:
        plt = _setup_mpl()
    except Exception:
        return ""

    keys = ["snr", "spatial_cov", "negative_fraction",
            "dvars_spike_fraction", "skewness", "qei", "tsnr", "mean_fd"]
    labels = ["SNR", "CoV", "Neg%", "DVARS", "Skew", "QEI", "tSNR", "FD"]

    data = []
    for s in subjects:
        row = []
        for k in keys:
            v = s.get(k)
            row.append(v if v is not None and _is_finite(v) else np.nan)
        data.append(row)

    arr = np.array(data)

    # drop columns that are all NaN
    valid_cols = ~np.all(np.isnan(arr), axis=0)
    arr = arr[:, valid_cols]
    labels_filtered = [l for l, v in zip(labels, valid_cols) if v]

    if arr.shape[1] < 2:
        return ""

    try:
        n_cols = arr.shape[1]
        corr = np.zeros((n_cols, n_cols))
        for i in range(n_cols):
            for j in range(n_cols):
                valid = ~(np.isnan(arr[:, i]) | np.isnan(arr[:, j]))
                if valid.sum() > 2:
                    corr[i, j] = np.corrcoef(arr[valid, i], arr[valid, j])[0, 1]
                else:
                    corr[i, j] = np.nan

        fig, ax = plt.subplots(figsize=(6, 5))
        im = ax.imshow(corr, cmap="coolwarm", vmin=-1, vmax=1, aspect="equal")

        ax.set_xticks(range(len(labels_filtered)))
        ax.set_yticks(range(len(labels_filtered)))
        ax.set_xticklabels(labels_filtered, fontsize=9, rotation=45, ha="right")
        ax.set_yticklabels(labels_filtered, fontsize=9)

        for i in range(len(labels_filtered)):
            for j in range(len(labels_filtered)):
                if math.isfinite(corr[i, j]):
                    color = "white" if abs(corr[i, j]) > 0.6 else "black"
                    ax.text(j, i, f"{corr[i,j]:.2f}", ha="center", va="center",
                            fontsize=8, color=color)

        fig.colorbar(im, ax=ax, shrink=0.8, label="Pearson r")
        fig.tight_layout()

        b64 = _fig_to_b64(fig)
        return f"""
<h2>Inter-Metric Correlations</h2>
<div class="plot-cell" style="max-width:600px">
<img src="data:image/png;base64,{b64}" alt="Correlation matrix">
</div>
"""
    except Exception:
        return ""


# ──────────────────────────────────────────────
# Anomaly plot (interactive SVG with hover)
# ──────────────────────────────────────────────

def _anomaly_section(subjects, if_results):
    if not subjects or len(subjects) < 3:
        return ""

    if if_results is None:
        return """
<h2>Anomaly Detection</h2>
<p style="color:#888">
Isolation forest was not run — fewer than 10 subjects
or scikit-learn not installed.
</p>
"""

    n_anom = if_results.get("n_anomalies", 0)

    # build interactive SVG scatter plot
    svg = _anomaly_svg(subjects)
    if not svg:
        return ""

    return f"""
<h2>Anomaly Detection</h2>
<p style="font-size:12px; color:#666">
Isolation forest flagged {n_anom} subject(s) as anomalous.
Hover over points to see subject IDs.
</p>
<div class="anomaly-container" id="anomaly-wrap">
<div class="tooltip" id="anomaly-tip"></div>
{svg}
</div>
{_anomaly_hover_js()}
"""


def _anomaly_svg(subjects):
    """Build an inline SVG scatter plot with data attributes for hover."""
    # collect data
    points = []
    for s in subjects:
        anom = s.get("anomaly_score")
        snr = s.get("snr")
        if anom is None or snr is None:
            continue
        if not _is_finite(anom) or not _is_finite(snr):
            continue
        points.append({
            "x": anom,
            "y": snr,
            "label": s.get("subject_id", "?"),
            "status": s.get("status", "PASS"),
            "is_anomaly": s.get("if_label", 1) == -1,
        })

    if len(points) < 2:
        return ""

    # coordinate mapping
    xs = [p["x"] for p in points]
    ys = [p["y"] for p in points]
    x_min, x_max = min(xs), max(xs)
    y_min, y_max = min(ys), max(ys)

    # add 5% padding
    x_pad = max((x_max - x_min) * 0.08, 0.1)
    y_pad = max((y_max - y_min) * 0.08, 0.5)
    x_min -= x_pad; x_max += x_pad
    y_min -= y_pad; y_max += y_pad

    w, h = 560, 360
    margin = {"l": 55, "r": 20, "t": 15, "b": 45}
    pw = w - margin["l"] - margin["r"]
    ph = h - margin["t"] - margin["b"]

    def sx(v):
        return margin["l"] + (v - x_min) / (x_max - x_min) * pw

    def sy(v):
        return margin["t"] + (1 - (v - y_min) / (y_max - y_min)) * ph

    lines = [f'<svg width="{w}" height="{h}" xmlns="http://www.w3.org/2000/svg" '
             f'style="background:#fff;font-family:Inter,system-ui,sans-serif">']

    # axes
    ax_y = margin["t"] + ph
    lines.append(f'<line x1="{margin["l"]}" y1="{margin["t"]}" '
                 f'x2="{margin["l"]}" y2="{ax_y}" stroke="#ccc" stroke-width="1"/>')
    lines.append(f'<line x1="{margin["l"]}" y1="{ax_y}" '
                 f'x2="{margin["l"]+pw}" y2="{ax_y}" stroke="#ccc" stroke-width="1"/>')

    # axis labels
    lines.append(f'<text x="{margin["l"]+pw//2}" y="{h-5}" '
                 f'text-anchor="middle" font-size="11" fill="#666">'
                 f'Anomaly score</text>')
    lines.append(f'<text x="14" y="{margin["t"]+ph//2}" '
                 f'text-anchor="middle" font-size="11" fill="#666" '
                 f'transform="rotate(-90,14,{margin["t"]+ph//2})">'
                 f'SNR</text>')

    # tick marks
    n_xticks = 5
    for i in range(n_xticks + 1):
        v = x_min + i * (x_max - x_min) / n_xticks
        px = sx(v)
        lines.append(f'<line x1="{px:.1f}" y1="{ax_y}" x2="{px:.1f}" '
                     f'y2="{ax_y+4}" stroke="#ccc" stroke-width="1"/>')
        lines.append(f'<text x="{px:.1f}" y="{ax_y+16}" text-anchor="middle" '
                     f'font-size="9" fill="#999">{v:.2f}</text>')

    n_yticks = 5
    for i in range(n_yticks + 1):
        v = y_min + i * (y_max - y_min) / n_yticks
        py = sy(v)
        lines.append(f'<line x1="{margin["l"]-4}" y1="{py:.1f}" '
                     f'x2="{margin["l"]}" y2="{py:.1f}" stroke="#ccc"/>')
        lines.append(f'<text x="{margin["l"]-8}" y="{py+3:.1f}" '
                     f'text-anchor="end" font-size="9" fill="#999">'
                     f'{v:.1f}</text>')
        # grid line
        lines.append(f'<line x1="{margin["l"]}" y1="{py:.1f}" '
                     f'x2="{margin["l"]+pw}" y2="{py:.1f}" '
                     f'stroke="#f0f0f0" stroke-width="0.5"/>')

    # data points
    for p in points:
        px, py = sx(p["x"]), sy(p["y"])
        if p["is_anomaly"]:
            color = "#e53935"
            r = 5
            # draw an X marker for anomalies
            d = 4
            lines.append(
                f'<g class="anom-pt" data-label="{p["label"]}" '
                f'data-anom="{p["x"]:.3f}" data-snr="{p["y"]:.1f}">'
                f'<circle cx="{px:.1f}" cy="{py:.1f}" r="8" '
                f'fill="transparent" stroke="none"/>'
                f'<line x1="{px-d:.1f}" y1="{py-d:.1f}" '
                f'x2="{px+d:.1f}" y2="{py+d:.1f}" '
                f'stroke="{color}" stroke-width="2"/>'
                f'<line x1="{px+d:.1f}" y1="{py-d:.1f}" '
                f'x2="{px-d:.1f}" y2="{py+d:.1f}" '
                f'stroke="{color}" stroke-width="2"/>'
                f'</g>'
            )
        else:
            color = "#aaa"
            lines.append(
                f'<circle class="anom-pt" cx="{px:.1f}" cy="{py:.1f}" r="4" '
                f'fill="{color}" fill-opacity="0.6" stroke="none" '
                f'data-label="{p["label"]}" '
                f'data-anom="{p["x"]:.3f}" data-snr="{p["y"]:.1f}"/>'
            )

    # legend
    lx = margin["l"] + pw - 90
    ly = margin["t"] + 12
    lines.append(f'<circle cx="{lx}" cy="{ly}" r="4" fill="#aaa" opacity="0.6"/>')
    lines.append(f'<text x="{lx+8}" y="{ly+3}" font-size="10" fill="#666">Normal</text>')
    # X marker for anomaly legend
    lx2 = lx
    ly2 = ly + 16
    lines.append(f'<line x1="{lx2-3}" y1="{ly2-3}" x2="{lx2+3}" y2="{ly2+3}" '
                 f'stroke="#e53935" stroke-width="2"/>')
    lines.append(f'<line x1="{lx2+3}" y1="{ly2-3}" x2="{lx2-3}" y2="{ly2+3}" '
                 f'stroke="#e53935" stroke-width="2"/>')
    lines.append(f'<text x="{lx2+8}" y="{ly2+3}" font-size="10" fill="#666">Anomaly</text>')

    lines.append('</svg>')
    return "\n".join(lines)


def _anomaly_hover_js():
    """JavaScript for hover tooltips on the anomaly SVG scatter."""
    return """
<script>
(function() {
    var wrap = document.getElementById('anomaly-wrap');
    if (!wrap) return;
    var tip = document.getElementById('anomaly-tip');
    var pts = wrap.querySelectorAll('.anom-pt');
    pts.forEach(function(el) {
        el.style.cursor = 'pointer';
        el.addEventListener('mouseenter', function(e) {
            var label = el.getAttribute('data-label');
            var anom = el.getAttribute('data-anom');
            var snr = el.getAttribute('data-snr');
            tip.textContent = label + '  (anomaly=' + anom + ', SNR=' + snr + ')';
            tip.style.display = 'block';
        });
        el.addEventListener('mousemove', function(e) {
            var rect = wrap.getBoundingClientRect();
            tip.style.left = (e.clientX - rect.left + 12) + 'px';
            tip.style.top = (e.clientY - rect.top - 24) + 'px';
        });
        el.addEventListener('mouseleave', function() {
            tip.style.display = 'none';
        });
    });
})();
</script>
"""


# ──────────────────────────────────────────────
# Subject status table (at the end now)
# ──────────────────────────────────────────────

def _subject_table(subjects):
    if not subjects:
        return ""

    sorted_subj = sorted(subjects,
                         key=lambda s: -(s.get("anomaly_score") or 0))

    rows = []
    for s in sorted_subj:
        status = s.get("status", "—")
        status_class = f"status-{status.lower()}"
        flagged = status == "FAIL" or (s.get("anomaly_score") or 0) > 1.5
        row_class = ' class="flagged"' if flagged else ""

        vals = {
            "snr": _fmt(s.get("snr"), ".1f"),
            "cov": _fmt(s.get("spatial_cov"), ".3f"),
            "neg": _fmt(s.get("negative_fraction"), ".3f"),
            "dvars": _fmt(s.get("dvars_spike_fraction"), ".2f"),
            "qei": _fmt(s.get("qei"), ".3f"),
            "tsnr": _fmt(s.get("tsnr"), ".1f"),
            "fd": _fmt(s.get("mean_fd"), ".3f"),
            "anom": _fmt(s.get("anomaly_score"), ".2f"),
        }

        rows.append(
            f'<tr{row_class}>'
            f'<td>{s.get("subject_id", "—")}</td>'
            f'<td class="{status_class}">{status}</td>'
            f'<td class="val">{vals["snr"]}</td>'
            f'<td class="val">{vals["cov"]}</td>'
            f'<td class="val">{vals["neg"]}</td>'
            f'<td class="val">{vals["dvars"]}</td>'
            f'<td class="val">{vals["qei"]}</td>'
            f'<td class="val">{vals["tsnr"]}</td>'
            f'<td class="val">{vals["fd"]}</td>'
            f'<td class="val">{vals["anom"]}</td>'
            f'</tr>'
        )

    return f"""
<h2>Subject Status</h2>
<table id="subject-table">
<tr>
    <th onclick="sortTable(0)">Subject <span class="sort-arrow">↕</span></th>
    <th onclick="sortTable(1)">Status <span class="sort-arrow">↕</span></th>
    <th onclick="sortTable(2)">SNR <span class="sort-arrow">↕</span></th>
    <th onclick="sortTable(3)">CoV <span class="sort-arrow">↕</span></th>
    <th onclick="sortTable(4)">Neg% <span class="sort-arrow">↕</span></th>
    <th onclick="sortTable(5)">DVARS <span class="sort-arrow">↕</span></th>
    <th onclick="sortTable(6)">QEI <span class="sort-arrow">↕</span></th>
    <th onclick="sortTable(7)">tSNR <span class="sort-arrow">↕</span></th>
    <th onclick="sortTable(8)">FD <span class="sort-arrow">↕</span></th>
    <th onclick="sortTable(9)">Anomaly <span class="sort-arrow">↕</span></th>
</tr>
{"".join(rows)}
</table>
"""


# ──────────────────────────────────────────────
# Methods footnote
# ──────────────────────────────────────────────

def _methods_footnote():
    return """
<div class="methods">
<h2>Methods</h2>
<p>
This cohort report was generated by the ASL QC Toolbox.
Per-subject quality metrics include: <strong>SNR</strong> (Rayleigh-corrected),
<strong>Spatial CoV</strong> (coefficient of variation),
<strong>DVARS</strong> (frame-to-frame signal change; Power et al. 2012,
doi:10.1016/j.neuroimage.2011.10.018),
<strong>QEI</strong> (Quality Evaluation Index; Dolui et al. 2024,
doi:10.1002/jmri.29308),
<strong>tSNR</strong> (temporal signal-to-noise ratio),
and <strong>framewise displacement</strong> (Power et al. 2012).
Negative voxel fraction is computed on the mean perfusion-weighted image
(pairwise control-label subtraction) for time-series data.
Cohort-level anomaly detection uses isolation forest (scikit-learn)
with contamination=0.1.  ASL acquisition standards follow Alsop et al.
(2015, doi:10.1002/mrm.25197).
</p>
</div>
"""


# ──────────────────────────────────────────────
# Sortable table JS
# ──────────────────────────────────────────────

def _sort_js():
    return """
<script>
var sortDirections = {};
function sortTable(colIndex) {
    var table = document.getElementById("subject-table");
    if (!table) return;
    var rows = Array.from(table.rows).slice(1);
    var dir = sortDirections[colIndex] || 'asc';
    dir = dir === 'asc' ? 'desc' : 'asc';
    sortDirections[colIndex] = dir;
    rows.sort(function(a, b) {
        var va = a.cells[colIndex].textContent.trim();
        var vb = b.cells[colIndex].textContent.trim();
        var na = parseFloat(va), nb = parseFloat(vb);
        if (!isNaN(na) && !isNaN(nb)) {
            return dir === 'asc' ? na - nb : nb - na;
        }
        return dir === 'asc' ? va.localeCompare(vb) : vb.localeCompare(va);
    });
    var tbody = table.tBodies[0] || table;
    rows.forEach(function(row) { tbody.appendChild(row); });
}
</script>
"""


# ──────────────────────────────────────────────
# Helpers
# ──────────────────────────────────────────────

def _fmt(val, fmt_str=".3f"):
    if val is None:
        return "—"
    try:
        if math.isfinite(val):
            return f"{val:{fmt_str}}"
    except (TypeError, ValueError):
        pass
    return "—"


def _is_finite(v):
    try:
        return math.isfinite(v)
    except (TypeError, ValueError):
        return False


def _setup_mpl():
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    plt.rcParams.update({
        'font.family': 'sans-serif',
        'font.sans-serif': ['DejaVu Sans', 'Arial', 'Helvetica'],
        'font.size': 10,
        'axes.spines.top': False,
        'axes.spines.right': False,
    })
    return plt


def _fig_to_b64(fig):
    buf = io.BytesIO()
    fig.savefig(buf, format="png", dpi=150, bbox_inches="tight",
                facecolor="white", edgecolor="none")
    import matplotlib.pyplot as plt
    plt.close(fig)
    return base64.b64encode(buf.getvalue()).decode()
